### ISSUE TITLE
Weekly SCRUM - April 8 2021

### ISSUE THREAD

**Issue by YoussefSaghbini** [MuneebNasir/Amazin-online-bookstore-OA#136]
Every team member should add comments with their own contribution, i.e. their answers to the questions:

    - What have I done this week? (with link(s) to the relevant GitHub Issue(s))
    - What will I do next week? (with link(s) to the relevant GitHub Issue(s))
    - What is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by MuneebNasir** [comment]
- What have I done this week? (with link(s) to the relevant GitHub Issue(s))

1. Updated the Author UI for enabling search and remove. #126 
2. Connected the Author and Publisher with the  drop-downs in Add Book Form #133 #109 
3. Updated the Controller tests accordingly #133 #109 
4. Worked on developing a  Cucumber test for the #107
5. Worked on developing Presentation Slides  

- What will I do next week? (with link(s) to the relevant GitHub Issue(s))
N/A
- What is holding me back? (if applicable)
N/A

**Comment by BoucherR** [comment]
- What have I done this week? (with link(s) to the relevant GitHub Issue(s))
1. Implemented Jaccard distance frontend and backend
2. Various fixes involving react components updating correctly
3. Updated front end forms to allow for proper creation of books with new categories added for Jaccard distance
4. Fixed table not displaying names correctly for publisher
5. Backend changes to allow for propery ONE TO MANY linking between books, authors, and publishers
- What will I do next week? (with link(s) to the relevant GitHub Issue(s))
N/A
- What is holding me back? (if applicable)
SYSC 4005

**Comment by decarbonite** [comment]
What have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Made only admin users can remove books/authors/publishers from the store #145 
- Added author to the book table #130 
- Fixed publication year #129 
- Refactored code from useless/unused/unneeded code #141 

What will I do next week? (with link(s) to the relevant GitHub Issue(s))

- We're done

What is holding me back? (if applicable)

- Same as BoucherR

**Comment by vanarman** [comment]
What have I done this week? (with link(s) to the relevant GitHub Issue(s))
- User access permission enforcement based on the role using Firebase authentication #125 
- Minor fixes
What will I do next week? (with link(s) to the relevant GitHub Issue(s))
- N/A
What is holding me back? (if applicable)
- N/A

**Comment by YoussefSaghbini** [comment]
- What have I done this week? (with link(s) to the relevant GitHub Issue(s))
Implemented Book Recommendation UI #108 
Helped Implementing the Jaccard Distance #121  #120 
Fixed Real-time data (since you need to refresh the page to get most recent data) #115 
Worked on Presentation for Cucumber Testing 

- What will I do next week? (with link(s) to the relevant GitHub Issue(s))
N/A

- What is holding me back? (if applicable)
N/A
