### ISSUE TITLE
Controller Overhaul

### ISSUE THREAD

**Issue by YoussefSaghbini** [MuneebNasir/Amazin-online-bookstore-OA#25]
We have discussed of removing the controllers and using built-in API with REST and Repository capabilities. This will make the system efficient and less runtime since the previous controllers are already extending CrudRepository to Repository.

We will still create test cases for each repository to test the APIs capabilities.

**Comment by YoussefSaghbini** [comment]
Old issues;
- #9 
- #2 
- #8 

These issues will be closed

**Comment by YoussefSaghbini** [comment]
@vanarman @decarbonite @BoucherR @MuneebNasir 

Requesting Approval from all contributors.

**Comment by MuneebNasir** [comment]
Sounds like a plan!

**Comment by BoucherR** [comment]
BE̖̯̰͍̗G̱͝I̢̜̘̺N̤͇̬ ͈͍̫̙T͚̗̫̞H̢͕̖ͅE͏̼̥̻̮̣̤ ̤͈͔̳̦̮̦T̫͔̻͘RAN̥̤͍͙̼̰ͅS̷͚F̻̮̩O̭̬̪͇͇̘̙R͓̯̲͚M͎͞A̢͓̣̼̘͖T̴̜͇̮͇͓͍̪Ì͎̠Ǫ̪̩̱̥N̞̠̲̰
